/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crop_prediction;

import au.com.bytecode.opencsv.CSVWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author DellUser
 */
public class cutom_form extends javax.swing.JFrame {

    /**
     * Creates new form cutom_form
     */
    public cutom_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        text_temp = new javax.swing.JTextField();
        text_ph = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        text_ec = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        text_days = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        menu_state = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Temperature");

        text_temp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_tempActionPerformed(evt);
            }
        });

        text_ph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_phActionPerformed(evt);
            }
        });

        jLabel3.setText("phValue of soil");

        jLabel4.setText("EC of soil");

        text_days.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_daysActionPerformed(evt);
            }
        });

        jLabel5.setText("No of days");

        menu_state.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "East India", "West India", "South India", "North India", " " }));

        jLabel6.setText("Location");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menu_state, 0, 147, Short.MAX_VALUE)
                    .addComponent(text_days)
                    .addComponent(text_ec)
                    .addComponent(text_ph))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(text_temp, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(115, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_ph, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_ec, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_days, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menu_state, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(text_temp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(246, Short.MAX_VALUE)))
        );

        jButton2.setText("Okay");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(jButton2)
                .addContainerGap(338, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(182, 182, 182)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(205, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(352, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(52, 52, 52))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(89, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_phActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_phActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_phActionPerformed

    private void text_daysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_daysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_daysActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        float pHvalue= Float.parseFloat(text_ph.getText());
        float Temp=Float.parseFloat(text_temp.getText());
        int EC=Integer.parseInt(text_ec.getText());
        int Months=Integer.parseInt(text_days.getText());
        int region=1;
       
        
        //pHvalue
        if(pHvalue< 3.5)
        {
            pHvalue=1;
        }
        else if(pHvalue>= 3.5 && pHvalue < 4.5)
        {
            pHvalue=2;
        }
         else if(pHvalue>=4.5 && pHvalue <= 5.0)
        {
            pHvalue=3;
        }
         else if(pHvalue>=5.1&& pHvalue <= 5.5)
        {
            pHvalue=4;
        }
          else if(pHvalue>=5.6&& pHvalue <= 6.0)
        {
            pHvalue=5;
        }
           else if(pHvalue>=6.1&& pHvalue <= 6.5)
        {
            pHvalue=6;
        }
           else if(pHvalue>=6.6&& pHvalue <= 7.3)
        {
            pHvalue=7;
        }
           else if(pHvalue>=7.4&& pHvalue <= 7.8)
        {
            pHvalue=8;
        }
        
        //EC
        if(EC>=0.8 && EC<1)
        {
            EC=1;
        }
        else if(EC>=1 && EC<1.2)
        {
            EC=2;
        }
         else if(EC>=1.2 && EC<1.4)
        {
            EC=3;
        }
         else if(EC>=1.4 && EC<1.6)
        {
            EC=4;
        }
         else if(EC>=1.6 && EC<1.8)
        {
            EC=5;
        }
         else if(EC>=1.8 && EC<2)
        {
            EC=6;
        }
         else if(EC>=2 && EC<2.2)
        {
            EC=7;
        }
         else if(EC>=2.2 && EC<2.4)
        {
            EC=8;
        }
         else if(EC>=2.4 && EC<2.6)
        {
            EC=9;
        }
         else if(EC>=2.6 && EC<2.8)
        {
            EC=10;
        }
         else if(EC>=2.8 && EC<3)
        {
            EC=11;
        }
        
        //region
        
        if(menu_state.getSelectedIndex()==0)
        {
            region=1;
        }
        else if(menu_state.getSelectedIndex()==1)
        {
            region=2;
        }
        else if(menu_state.getSelectedIndex()==2)
        {
            region=3;
        }
        else if(menu_state.getSelectedIndex()==3)
        {
            region=4;
        }
        
        //System.out.println(region+)
        //Creating CSV
        File file = new File("E:/trail.csv"); 
    try { 
        // create FileWriter object with file as parameter 
        FileWriter outputfile = new FileWriter(file); 
  
        // create CSVWriter object filewriter object as parameter 
        CSVWriter writer = new CSVWriter(outputfile); 
  
        // adding header to csv 
        String[] header = { "pHvalue", "Temp", "EC","Months","Region" }; 
        writer.writeNext(header); 
  
        // add data to csv 
        String p= Float.toString(pHvalue);
        String t= Float.toString(Temp);
        String ec=Integer.toString(EC);
        String m=Integer.toString(Months);
        String d =Integer.toString(region);
        
        String[] data1 = { p,t,ec,m,d }; 
        writer.writeNext(data1); 
        
  
        // closing writer connection 
        writer.close(); 
    } 
    catch (IOException e) { 
        // TODO Auto-generated catch block 
        e.printStackTrace();
    }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void text_tempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_tempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_tempActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cutom_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cutom_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cutom_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cutom_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cutom_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox menu_state;
    private javax.swing.JTextField text_days;
    private javax.swing.JTextField text_ec;
    private javax.swing.JTextField text_ph;
    private javax.swing.JTextField text_temp;
    // End of variables declaration//GEN-END:variables
}
